version: '3.2'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/01-init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_pass
